name:    services-gaffer
version: "0.0.0"

dependencies:
- aeson
- base
- blaze-markup
- bytestring
- containers
- directory
- gitlib
- gitlib-cmdline == 3.1.0.2
- http-conduit
- optparse-applicative
- shelly
- text
- wai
- wai-cors
- warp
- yesod-core
- yesod-auth
- yesod-auth-oauth2
- yesod-form

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  services-gaffer:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - services-gaffer
