apiVersion: v1
kind: Secret
metadata:
  name: {{ include "el-patron.fullname" . }}
  labels:
    app: {{ include "el-patron.name" . }}
    chart: {{ include "el-patron.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  githubClientId: "{{ .Values.elPatron.githubClientId | b64enc }}"
  githubClientSecret: "{{ .Values.elPatron.githubClientSecret | b64enc }}"
  privateKey: "{{ .Values.elPatron.privateKey | b64enc }}"
  known_hosts: "{{ .Values.elPatron.known_hosts | b64enc }}"
